export const TEST_REDUX = 'TEST_REDUX';

export const SAVE_NAME_TABLE='SAVE-NAME-TABLE';
export const SAVE_NAME_DESCRIPTION='SAVE_NAME_DESCRIPTION';
export const SAVE_NAME_TABLE_ITEM='SAVE_NAME_TABLE_ITEM';
export const SAVE_NAME_DESCRIPTION_ITEM='SAVE_NAME_DESCRIPTION_ITEM';
export const SAVE_DEADLINE='SAVE_DEADLINE';
export const SAVE_DEADLINE_TOTAL='SAVE_DEADLINE_TOTAL';
export const SAVE_LOCATION='SAVE_LOCATION';